### ISSUE TITLE
Welcome Spectrum Finance to Terra!

### ISSUE THREAD

**Issue by Cle4ncuts** [spectrumprotocol/contracts#2]
Hello there! Glad I get to bet the first to write this. Looking forward to the audit as well as future participation in this project.

Would love to get to know the team better as well as ambitions, roadmap, etc.

Is there plans for a discord community?

Cheers 😎

**Comment by hikari042** [comment]
@Cle4ncuts Please join the Telegram Channel at https://t.me/spec_finance
