### ISSUE TITLE
not able to withdraw

### ISSUE THREAD

**Issue by holajoyce** [spectrumprotocol/contracts#24]
Hello SPEC devs & admins,

I had been trying to perform some transactions with my terra station wallet on SPEC.   I've tried various other types of transactions on SPEC as well such as unstake gov tokens, and they've all failed as well (Oct 1, 2021).  I've also tested that my terra wallet works without error, by performing some small exchange transactions using the desktop terra wallet.  

In any case, here's the withdraw transaction that I'm interested in performing but was unable due to failure.  Here's my system info.

I have macos Mojave; chromium version 88.0.4324.150 (x86_64); using the terra station chrome plugin.  Trying to withdraw Spec-UST LP.  I've clicked on that box for that LP, clicked withdraw tab, clicked MAX, clicked withdraw (pink) button; then it asks me to confirm transaction, then I press the pink 'confirm' button, which causes Terra station plugin to popup, where it asks me to confirm with password, which I did, and Terra station chrome extenstion looked like it worked, but then on the Spectrum page, it shows error.  Furthermore, I've clicked on the referenced hash string, and on the https://finder.extraterrestrial.money/columbus-5/tx/... page it says status failed, with error msg: "
failed to execute message; message index: 0: Error parsing into type spectrum_protocol::spec_farm::ExecuteMsg: unknown variant `...`, expected one of `receive`, `register_asset`, `unbond`, `update_config`, `withdraw`: execute wasm contract failed".  I can send you the transaction hash in private if needed.

I also went to desktop terra station wallet and looked at the `history` tab on the sidebar, and it showed all the same errors as the  _finder.extraterrestrial.money_ page

The last time I was able to successfully perform transactions on SPEC protocol was September 24th, 2021, before switching to columbus 5.

Here you can see some of the failures
https://finder.terra.money/columbus-5/address/terra1s5eczhe0h0jutf46re52x5z4r03c8hupacxmdr

**Comment by SpectrumRhealward** [comment]
Hello @holajoyce 

Can you please send me your failed tx to spectrum.rhealward@gmail.com
And I assume that once you try again, withdraw was success, right?

If not, please take screenshot of Terra Station with expanded ExecuteMsgs, so that I can check if message is being sent to Terra Station correctly.

**Comment by SpectrumRhealward** [comment]
@holajoyce  and what is your Terra Station extension version? Did it get auto-update? I am using 1.15.2

**Comment by holajoyce** [comment]
hi @SpectrumRhealward , I was speaking with one of you guys on telegram, and was advised to remove and reinstall the chrome wallet extension.  I've followed the advice, and everything is working once again.  Do you guys still want me to send over failed tx hashes?  Thank you for your help.  I'll close this ticket now.

**Comment by holajoyce** [comment]
hi @SpectrumRhealward , I was speaking with one of you guys on telegram, and was advised to remove and reinstall the chrome wallet extension.  I've followed the advice, and everything is working once again.  Do you guys still want me to send over failed tx hashes?  Thank you for your help.  I'll close this ticket now.

**Comment by SpectrumRhealward** [comment]
@holajoyce no, it is not needed. My assumption is your Terra Station extension did not get auto updated.
