### ISSUE TITLE
Unable to unstake gov tokens from MINE-UST LP

### ISSUE THREAD

**Issue by ArtZab0** [spectrumprotocol/contracts#41]
When I try to unstake governance token from MINE-UST LP it gives the following error:
"rpc error: code = InvalidArgument desc = failed to execute message; message index: 1: dispatch: Error parsing into type pylon_token::gov_msg::ExecuteMsg: unknown variant `withdraw_voting_tokens`, expected one of `receive`, `update_config`, `poll`, `staking`, `airdrop`: execute wasm contract failed: invalid request"

![image](https://user-images.githubusercontent.com/47839240/142974176-c074b7b3-7f7e-4d62-a6f8-efe84cfcee17.png)

**Comment by SpectrumRhealward** [comment]
@ArtZab0 we are about to fix it right now
https://github.com/spectrumprotocol/contracts/pull/43
