### ISSUE TITLE
VKRUST LP

### ISSUE THREAD

**Issue by Cryptograk** [spectrumprotocol/contracts#45]
I'm not sure if this is a Spectrum issue or a Valkyrie issue.  Because VKR no longer compounds, I removed my liquidity.  However, I removed it as VKR-UST LP and was going to deposit it back on Valkyrie.

However, there is no option to deposit the LP on VKR, just the individual VKR + UST and now I have no way to convert the LP to the individual tokens.  I know this is probably a question for Valkyrie, but your customer support is infinitely better, and I'm open to any suggestions.

**Comment by Visionary1** [comment]
go to Terraswap and withdraw your LP

**Comment by SpectrumRhealward** [comment]
@Cryptograk https://app.terraswap.io/#Withdraw and withdraw tab

**Comment by Cryptograk** [comment]
Thanks.  I didn't even consider that.  Smh.
