### ISSUE TITLE
Add Luna bLUNA lp token with spec farming

### ISSUE THREAD

**Issue by massnomis** [spectrumprotocol/contracts#5]
https://velocity-app.flipsidecrypto.com/dashboard/burn-bluna-baby-bburn-LENGcb

makes good returns, low risk, i already lp here

**Comment by spectrum-lumiere** [comment]
Spectrum required host farm to operate (Mirror, Anchor). We need farm to provide rewards. Then Spectrum can make yield optimizer vault.

Close for now
